variable access_key {}
variable secret_key {}
variable "region" {}
variable "domain" {}
variable "api_key" {}
variable "email" {}
variable "vault_name" {}
variable "consul_name" {}
variable "zone_id" {}